services:
  db:
    image: postgres:15
    container_name: fifo-db
    environment:
      POSTGRES_USER: items_user
      POSTGRES_PASSWORD: items_pass
      POSTGRES_DB: items_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: postgres:15
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      sh -c "until pg_isready -h db -U items_user;
             do echo 'Waiting for Postgres...'; sleep 2; done;
             psql -h db -U items_user -d items_db -f /migrations/0001_create_items.sql"
    environment:
      PGPASSWORD: items_pass

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fifo-app:local
    container_name: fifo-app
    depends_on:
      - db
      - migrate
    environment:
      DB_HOST: db
      DB_USER: items_user
      DB_PASS: items_pass
      DB_NAME: items_db
    ports:
      - "8080:8080"

volumes:
  db_data:
