version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: items_user
      POSTGRES_PASSWORD: items_pass
      POSTGRES_DB: items_db
    ports:
      - "5432:5432"
